export const ACTION_TYPE = {
  INITIALISE_PRODUCTS: "INITIALISE_PRODUCTS",
  INITIALISE_CATEGORIES: "INITIALISE_CATEGORIES",
  INITIALISE_FEATURES: "INITIALISE_FEATURES",
  FEATURE_FILTER: "FEATURES_FILTER",
  CATEGORY_FILTER: "CATEGORY_FILTER",
  RATING_FILTER: "RATING_FILTER",
  SORTING_FILTER: "SORTING_FILTER",
  PRICE_FILTER: "PRICE_FILTER",
  NO_FILTER: "NO_FILTER",
};
